const dataSchema = "[\n    {\n      'id': 'path',\n      'value': value\n    },\n    {\n      'id': 'path',\n      'value': value\n    },\n    //insert additional object data sets\n  ]";

const docs = [
  {
    variable: 'width',
    value: 800,
    dataType: 'Number',
    description: 'The outer width of the chart, in pixels.',
    defaultValue: 800,
    min: 300,
    max: 1500,
  },
  {
    variable: 'overlap',
    value: 1,
    dataType: 'Number',
    description: 'The overlap between each ridgeline.',
    defaultValue: 1,
    min: 0,
    max: 10,
  },
  {
    variable: 'verticalScale',
    value: 17,
    dataType: 'Number',
    description: 'The vertical spacing between each y axis ticks.',
    defaultValue: 17,
    min: 10,
    max: 100,
  },
  {
    variable: 'marginTop',
    value: 40,
    dataType: 'Number',
    description: 'The top margin, in pixels.',
    defaultValue: 40,
    min: 1,
    max: 100,
  },
  {
    variable: 'marginRight',
    value: 0,
    dataType: 'Number',
    description: 'The right margin, in pixels.',
    defaultValue: 0,
    max: 100,
  },
  {
    variable: 'marginBottom',
    value: 40,
    dataType: 'Number',
    description: 'The bottom margin, in pixels.',
    defaultValue: 40,
    min: 1,
    max: 100,
  },
   {
    variable: 'marginLeft',
    value: 60,
    dataType: 'Number',
    description: 'The left margin, in pixels.',
    defaultValue: 60,
    min: 1,
    max: 100,
  },
  {
    variable: 'yAxisOffset',
    value: 0,
    dataType: 'Number',
    description: 'The vertical offset of y-axis labels, in pixels.',
    defaultValue: 0,
    min: -20,
    max: 10,
  },
];
