import { writable } from 'svelte/store';

export const PieChartDocs = writable([
  {
    variable: 'data',
    value: 'sampleData',
    dataType: 'CSV/Array',
    description:
      'A CSV will need to be parsed to fit the data schema above. The array will hold objects with the first key value pair being the data being tracked and its associated label, the second being the count or frequency and its associated label.',
    defaultValue: 'pie-data-census',
  },
  {
    variable: 'height',
    value: 600,
    dataType: 'Number',
    description: 'Height of the SVG container',
    defaultValue: 600,
    max: 700,
    min: 200,
  },
  {
    variable: 'width',
    value: 600,
    dataType: 'Number',
    description: 'Width of the SVG container',
    defaultValue: 600,
    max: 700,
    min: 200,
  },
  {
    variable: 'percent',
    value: true,
    dataType: 'Boolean',
    description: 'Will display data as a percentage or value',
    defaultValue: true,
  },
  {
    variable: 'stroke',
    value: 2,
    dataType: 'Number',
    description: 'The width of the stroke, in pixels.',
    defaultValue: 2,
    max: 10,
    min: 1,
  },
  {
    variable: 'outerRadius',
    value: 0.5,
    dataType: 'Number',
    description: 'Outer Radius of the pie.',
    defaultValue: 0.5,
    max: 1,
    min: 0.1,
  },
  {
    variable: 'innerRadius',
    value: 4,
    dataType: 'Number',
    description: 'The inner width of the negative space, in pixels.',
    defaultValue: 4,
    //may need to fix the min and max properties to be reversed
    max: 1,
    min: 5,
  },
  {
    variable: 'labelRadius',
    value: 0.7,
    dataType: 'Number',
    description: 'The location where the raw data displays on the wedge.',
    defaultValue: 0.7,
    max: 0.9,
    min: 0.3,
  },
  {
    variable: 'colorRangeStart',
    value: 0.6,
    dataType: 'Number',
    description:
      'The starting point for the color range displayed on each wedge.',
    defaultValue: 0.4,
    max: 0.7,
    min: 0,
  },
  {
    variable: 'strokeColor',
    value: 'none',
    dataType: 'String',
    description: 'The color of the line separating each wedge.',
    defaultValue: 'none',
  },
]);
